export const STORE_LOCATION = __dirname + "/../../store";

export const SUGGESTION_TYPES = {
	ADD_FIELDS_TO_INDEX: "ADD_FIELDS_TO_INDEX",
	CHANGE_RANGE_TO_FOLLOW_ESR: "CHANGE_RANGE_TO_FOLLOW_ESR",
	CHANGE_SORT_KEYS_TO_FOLLOW_ESR: "CHANGE_SORT_KEYS_TO_FOLLOW_ESR",
	ADD_FIELD_FOR_COVERED_QUERY: "ADD_FIELD_FOR_COVERED_QUERY",
	CREATE_ESR_INDEX: "CREATE_ESR_INDEX",
	REMOVE_ID_PROJECTION_FROM_PROJECTION: "REMOVE_ID_PROJECTION_FROM_PROJECTION",
	REMOVE_FIELDS_FROM_PROJECTION: "REMOVE_FIELDS_FROM_PROJECTION",
	SORT_BEFORE_GROUP_FIRST: "SORT_BEFORE_GROUP_FIRST",
	SORT_BEFORE_INTERVENE: "SORT_BEFORE_INTERVENE",
	MATCH_BEFORE_GROUP: "MATCH_BEFORE_GROUP",
	ADD_MATCH_FIRST_STAGE: "ADD_MATCH_FIRST_STAGE",
	MOVE_MATCH_FIRST_STAGE: "MOVE_MATCH_FIRST_STAGE"
};