site_name: Abbot
docs_dir: 'pages'
pages:
  - 'Home': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Reference': 'api.md'
  - 'Concept': 'concept.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wheredevsdev/abbot
