site_name: Abbot
docs_dir: 'pages'
nav:
  - 'Home': 'index.md'
  - 'Getting Started': 'getting-started.md'
  - 'Reference': 'api.md'
  - 'Concept': 'concept.md'
theme:
  name: material
  icon:
    logo: material/book-open-page-variant-outline
  favicon: ./img/abbotlogo.png
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.instant
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wheredevsdev/abbot
extra_css:
  - stylesheets/extra.css
